config/routes.rb
Rails.application.routes.draw do

  resources :restaurants, only: [ :index, :show, :new, :create ] do
    resources :reviews, only: [ :create ]
  end

  # root to: "controller#action"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    has_many :reviews, dependent: :destroy

    CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"]

    validates :name, presence: true
    validates :address, presence: true
    validates :category, presence: true, inclusion: { in: CATEGORIES }

end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :restaurant

    validates :content, presence: true
    validates :rating, presence: true, inclusion: { in: 0..5 }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
    def index
        @restaurants = Restaurant.all
    end

    def show
        @restaurant = Restaurant.find(params[:id])
        @review = Review.new
    end

    def new
        @restaurant = Restaurant.new
    end

    def create
        @restaurant = Restaurant.new(restaurant_params)
        @restaurant.save
        redirect_to restaurants_path(@restaurant)
    end



    private

    def restaurant_params
        params.require(:restaurant).permit(:name, :address, :category, :phone_number)
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
   
      def create
        @review = Review.new(review_params)
        # we need `restaurant_id` to associate review with corresponding restaurant
        @restaurant = Restaurant.find(params[:restaurant_id])
        @review.restaurant = @restaurant
        if @review.save
          redirect_to restaurant_path(@restaurant)
        else
          render :new
        end
      end

      private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item active">
					<%= link_to "Home", "#", class: "nav-link" %>
				</li>
				<li class="nav-item">
					<%= link_to "Messages", "#", class: "nav-link" %>
				</li>
				<li class="nav-item dropdown">
					<%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
					<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
						<%= link_to "Action", "#", class: "dropdown-item" %>
						<%= link_to "Another action", "#", class: "dropdown-item" %>
					</div>
				</li>
			</ul>
		</div>
	</div>

    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for(restaurant) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :category %>
  <%= f.text_field :category %>
  <%= f.label :phone_number %>
  <%= f.number_field :phone_number %>
  <%= f.submit %>
<% end %>

app/views/restaurants/_review_form.html.erb
<%= simple_form_for [ restaurant, review ] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>

<% end %>

app/views/restaurants/index.html.erb
<h1>Liste de tout les restaurants<h1>


<ul>
  <% @restaurants.each do |restaurant| %>
    <li>
      <%= link_to restaurant.name, restaurant_path(restaurant.id)  %>
    <li>
  <% end %>
</ul>

<%= link_to "Add a restaurant", new_restaurant_path  %>

app/views/restaurants/new.html.erb
<h1>Créer un nouveau restaurant<h1>

<%= render "form", restaurant: @restaurant %>

<%= link_to "Back to index",  restaurants_path %>

app/views/restaurants/show.html.erb
<h1>Hello world</h1>

<h2>
  <%= @restaurant.name  %>
</h2>

<h3>
  <%= @restaurant.address %>
</h3>

<h3>
  <%= @restaurant.phone_number %>
</h3>


<h3>
  <%= @restaurant.category %>
</h3>




<ul>
  <% @restaurant.reviews.each do |review|  %>
    <li>
  <%= review.content  %>
  <%= review.rating %>
    </li>
  <% end  %>
</ul>

<%= render "review_form", restaurant: @restaurant, review: @review %>

<%= link_to "Back to list", restaurants_path %>